---
version: 1.0.0
settings:
  '# log': Either server or file
  log: server
  '# dest': If file, this is a filename, otherwise emergency|alert|critical|error|warning|notice|info|debug
  dest: info
  '# default': If true, will start logging by default
  default: false
'# privacy': regular expressions and replacements used for ensuring privacy
privacy:
  /\/login\s*.*/: /login **CENSORED**
...
