name: ChatScribe
version: 1.1.0
main: aliuly\chatscribe\Main
api: 1.10.0
load: POSTWORLD

description: Logs chats and commands
author: aliuly

commands:
  log:
    description: Enable/disable logging
    usage: "/log [on|off]"
    permission: chatscribe.cmd

permissions:
 chatscribe.cmd:
   default: op
   description: "Enable logging"
 chatscribe.privacy:
   default: false
   description: "No logging"
