name: Mobsters
version: 0.5.0
api: [1.12.0]
load: STARTUP
main: aliuly\mobsters\Main

author: aliuly
description: A simple Entity implementation

commands:
  mobster:
    description: "Spawn a mob"
    usage: "/mobster [spawn] <name> <x,y,z[,yaw,pitch][:world]>"
    aliases: [mob]
    permission: mobsters.cmd

permissions:
  mobsters.cmd:
    default: op
    description: "Allow mobster commands"
  mobsters.cmd.spawn:
    default: op
    description: "Allow to spawn mobs by command line"
