main: aliuly\liab\Main
api: 1.10.0
load: POSTWORLD

name: LIAB
description: Leave It All Behind
version: 1.0.0
author: aliuly

permissions:
    liab.keep:
        default: false
        description: "Players with this permission get to keep it all"
