name: LocalChat
version: 1.2.1
main: aliuly\localchat\Main
api: 1.10.0
load: POSTWORLD

description: Chatting is localized to a certain area
author: aliuly

permissions:
  localchat.broadcast:
    default: true
    description: "Give players the ability to broadcast messages"
  localchat.broadcast.server:
    default: op
    description: "Broadcast to the server"
  localchat.broadcast.level:
    default: true
    description: "Broadcast to the level"
  localchat.spy:
    default: true
    description: "Grant players the ability to spy on players"
